# Generated by Django 5.1.3 on 2024-11-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Datasets_Details",
            fields=[
                ("dataset_id", models.AutoField(primary_key=True, serialize=False)),
                ("dataset_name", models.FileField(null=True, upload_to="")),
                ("file_size", models.CharField(max_length=100)),
                ("formated_file_size", models.CharField(max_length=100, null=True)),
                ("date_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "datasets_details",
            },
        ),
        migrations.CreateModel(
            name="Decision_Tree_Algo",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("Accuracy", models.TextField(max_length=100)),
                ("Precession", models.TextField(max_length=100)),
                ("F1_Score", models.TextField(max_length=100)),
                ("Recall", models.TextField(max_length=100)),
                ("Name", models.TextField(max_length=100)),
            ],
            options={
                "db_table": "decision_tree_algo",
            },
        ),
        migrations.CreateModel(
            name="Logistic_Regression",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("Accuracy", models.TextField(max_length=100)),
                ("Precession", models.TextField(max_length=100)),
                ("F1_Score", models.TextField(max_length=100)),
                ("Recall", models.TextField(max_length=100)),
                ("Name", models.TextField(max_length=100)),
            ],
            options={
                "db_table": "logistic_regression_algo",
            },
        ),
        migrations.CreateModel(
            name="SVM_algo",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("Accuracy", models.TextField(max_length=100)),
                ("Precession", models.TextField(max_length=100)),
                ("F1_Score", models.TextField(max_length=100)),
                ("Recall", models.TextField(max_length=100)),
                ("Name", models.TextField(max_length=100)),
            ],
            options={
                "db_table": "SVM_algo",
            },
        ),
    ]
